name: Discord Notification
on:
  push:
  pull_request:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set image URL based on event
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "image_url=https://raw.githubusercontent.com/razaele0003/PracticeFIle/main/Holder/Push.jpg" >> $GITHUB_OUTPUT
          else
            echo "image_url=https://raw.githubusercontent.com/razaele0003/PracticeFIle/main/Holder/Pull.jpg" >> $GITHUB_OUTPUT
          fi

      - name: Send Discord message with image
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "username": "KenBoth",
            "avatar_url": "https://raw.githubusercontent.com/razaele0003/PracticeFIle/main/Holder/Prof.jpg",
            "embeds": [{
              "color": 5763719,
              "fields": [
                {
                  "name": "Repository",
                  "value": "'"${{ github.repository }}"'",
                  "inline": true
                },
                {
                  "name": "Ref",
                  "value": "'"${{ github.ref }}"'",
                  "inline": true
                },
                {
                  "name": "Event - '"${{ github.event_name }}"'",
                  "value": "'"${{ github.sha }}"' '"${{ github.event.head_commit.message }}"'",
                  "inline": false
                },
                {
                  "name": "Triggered by",
                  "value": "'"${{ github.actor }}"'",
                  "inline": true
                },
                {
                  "name": "Workflow",
                  "value": "Discord Notification",
                  "inline": true
                }
              ],
              "image": {
                "url": "'"${{ steps.vars.outputs.image_url }}"'"
              }
            }]
          }'
